# conda env create --file environment.yml
# mamba env create --file environment.yml
name: customer_segmentation
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - missingno
  - nbdime
  - numpy
  - pandas
  - pip
  - plotly
  - pyjanitor
  - pyprojroot
  - python=3.9
  - seaborn
  - upsetplot
